name: Auto Green

on:
  schedule:
    - cron: '30 16 * * *' # 北京时间凌晨 00:30 自动运行
  workflow_dispatch:      # 允许你手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true # 确保有权限推回代码

      - name: Update Heartbeat
        run: |
          # 这一步是产生文件变动，否则没法 commit
          echo "Last Sync: $(date)" > heartbeat.txt

      - name: Auto Commit
        run: |
          git config --local user.email "3561123798@qq.com"
          git config --local user.name "EunoiaOvO"
          git add heartbeat.txt
          git commit -m "chore: nightly sync"
          git push
